{% set name = "pytest-astropy-header" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77891101c94b75a8ca305453b879b318ab6001b370df02be2c0b6d1bb322db10

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python
    - pytest >=4.6

test:
  source_files:
    - tests/
  imports:
    - pytest_astropy_header
    - pytest_astropy_header.display
  requires:
    - pip
    - pytest
    - astropy >=4.0
    - numpy
  commands:
    - pip check
    - pytest tests -vv

about:
  home: https://github.com/astropy/pytest-astropy-header
  license_family: BSD
  license: BSD 3-Clause
  license_file: LICENSE.rst
  summary: 'Pytest plugin to add diagnostic information to the header of the test output'
  doc_url: https://github.com/astropy/pytest-astropy-header
  dev_url: https://github.com/astropy/pytest-astropy-header

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - bsipocz
